FLAP_THRESHOLD = 0.8

POPULATION = 50

SURVIVORS = 10

# Randomizing
WEIGHT_SMALL_MUTATION_PROB = 1
WEIGHT_BIG_MUTATION_PROB = 1

# Neural network
INPUT_NEURONS = 4 # Bird.y / Pipes.x / TopPipe.y / BotPipe.y
HIDDENS = [3]
OUTPUT_NEURONS = 1
TOPOLOGY = [INPUT_NEURONS] + HIDDENS + [OUTPUT_NEURONS]
